//
import Image from 'next/image';
import { Inter } from 'next/font/google';
import { COLORS } from '@/theme/COLORS';
import { Avatar } from '@mui/material';
import heroBg from '../assets/hero-bg1.jpeg';
import { customStyle } from '@/theme/CustomeStyle';
import { Navbar, HeroSection, SectionTitle, SpeedDialTooltipOpen, AccountMenu, ContactUsSection, AboutUsSection, ServicesSection } from '@/components';
import Head from 'next/head'
import { Footer } from '@/components';
import { store } from '../store';
import { Provider } from 'react-redux'
//
const inter = Inter({ subsets: ['latin'] });
//
export default function Home() {
  return (
    <main className={`flex bg-[#ffffff] flex-col items-center justify-between`}>
      <Head>
        <title>Murat </title>
        <meta name="escription" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon_io/favicon.ico" />
      </Head>
      {/* Header */}
      <section id='home' className={`w-[100%] flex items-center h-[7vh] bg-gradient-to-r from-[#22438fe8] via-slate-50 to-slate-50 px-5`}>
        <Navbar />
      </section>
      {/* Hero Section */}
      <section style={{ backgroundImage: `url(${heroBg.src})` }} className={`w-[100%] bg-no-repeat bg-cover bg-center sm:h-[85vh] ${customStyle.flexCenter}`}>
        <div className={`w-[100%] ${customStyle.boxWidth} bg-[#22438fe8] sm:h-[100%] px-3 sm:px-10  flex items-center justify-center`}>
          <HeroSection />
        </div>
      </section>
      {/* Services Section */}
      <section id="services" className={`w-[100%] min-h-[70vh] bg-[#fafafa] p-4 sm:p-10 `}>
        <SectionTitle title="Our-Services" />
        <ServicesSection />
      </section>
      {/* About-us Section */}
      <section id="about-us" className={`w-[100%] min-h-[70vh] bg-[#ffffff] p-4 sm:p-10 `}>
        <SectionTitle title="About-us" />
        <AboutUsSection />
      </section>
      {/* Contact-us Section */}
      <section id="contact-us" className={`w-[100%] sm:min-h-[80vh]  bg-[#fafafa] p-4 sm:p-14 `}>
        <SectionTitle title="Contact-us" />
        <ContactUsSection />
      </section>
      {/* Footer Section */}
      <section className={`w-[100%] sm:min-h-[30vh]  bg-slate-700 p-4 sm:p-14 `}>
        <Footer />
      </section>
      {/* <SpeedDialTooltipOpen /> */}
    </main>
  )
}
//